[package]
name = "udp-tcp-test"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = { version = "*", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
dotenvy = "0.15"